name: CI

on:
    push:
        branches: main
        # paths: ['**.cpp', '**.h', '**CMakeLists.txt'] 
    pull_request:
        branches: main
        # paths: ['**.cpp', '**.h', '**CMakeLists.txt']

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            # Install Oracle Java 17 using the setup-java GitHub Action
            - name: Install Java
              uses: actions/setup-java@v4
              with:
                distribution: 'oracle' # Specify the distribution of Java
                java-version: '17' # Specify the version of Java to install
            
            - name: Set up Minecraft testing environment
              uses: nhatdongdang/setup-mc-action@v1

            # Checkout the mcpp repository for building and testing
            - name: Checkout mcpp
              uses: actions/checkout@v4

            # Build files using CMake
            - name: Build file
              run: cmake -Bbuild

            # Run the test suite using ctest
            - name: Run test suite
              working-directory: ./build
              run: make test_suite && ctest -R full