name: CI

on:
    push:
        branches: main
        paths: ['**.cpp', '**.h', '**CMakeLists.txt'] 
    pull_request:
        branches: main
        paths: ['**.cpp', '**.h', '**CMakeLists.txt']

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            # Install Oracle Java 17 using the setup-java GitHub Action
            - name: Install Java
              uses: actions/setup-java@v4
              with:
                distribution: 'oracle' # Specify the distribution of Java
                java-version: '17' # Specify the version of Java to install
            
            - name: Install Dotnet
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '7.0.408'
            
            # Clone the Minecraft_Tools repository from GitHub, which includes all necessary tools for the Spigot server 
            - name: Clone Minecraft_Tools
              run: git clone https://github.com/nhatdongdang/Minecraft_Tools
            
            # Start the Spigot server using terminal commands
            - name: Start Spigot Server
              working-directory: ./Minecraft_Tools/server
              run: nohup java -Xms512M -Xmx1024M -jar -DIReallyKnowWhatIAmDoingISwear spigot-1.19.4.jar nogui -o true & sleep 45

            - name: Clone Minecraft-Console-Client
              run: git clone https://github.com/MCCTeam/Minecraft-Console-Client
            
            - name: Build Minecraft-Console-Client
              working-directory: ./Minecraft-Console-Client
              run: dotnet publish MinecraftClient -f net7.0 -r linux-x64 --no-self-contained -c Release -p:UseAppHost=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=None

            # Join the Spigot server using the precompiled Minecraft-Console-Client (https://github.com/MCCTeam/Minecraft-Console-Client). 
            # The config file: https://github.com/nhatdongdang/Minecraft_Tools/blob/main/MinecraftClient/MinecraftClient.ini
            - name: Join Spigot Server
              working-directory: ./Minecraft-Console-Client/MinecraftClient/bin/Release/net7.0/linux-x64/MinecraftClient
              run: ./MinecraftClient && testbot && - && ::1 & sleep 5

            # Checkout the mcpp repository for building and testing
            - name: Checkout mcpp
              uses: actions/checkout@v4

            # Build files using CMake
            - name: Build file
              run: cmake -Bbuild

            # Run the test suite using ctest
            - name: Run test suite
              working-directory: ./build
              run: make test_suite && ctest -R full